# ----------------------------------------------------
# VULNERABLE SMB CONFIG - BNK DIGITAL LAB
# ----------------------------------------------------

[global]
   workgroup = WORKGROUP
   server string = Samba Server %v
   netbios name = BNK-DIGITAL
   security = user
   
   # --- CELAH UTAMA: GUEST ACCESS ---
   # Jika login gagal, otomatis dijadikan 'guest' (tamu)
   map to guest = bad user
   dns proxy = no

# --- FOLDER SHARE YANG BOCOR ---
[public]
   comment = Data Publik Nasabah
   path = /srv/samba/public
   browseable = yes
   read only = yes
   
   # --- CELAH: IZINKAN TANPA PASSWORD ---
   guest ok = yes
   public = yes