# ----------------------------------------------------
# VULNERABLE CONFIGURATION - BNK DIGITAL LAB
# ----------------------------------------------------

listen=NO
listen_ipv6=YES

# --- CELAH UTAMA: ANONYMOUS ACCESS ---
# Izinkan login tanpa user & password
anonymous_enable=YES
no_anon_password=YES

# Tentukan folder "tamu" (tempat flag diletakkan)
anon_root=/var/ftp

local_enable=YES
write_enable=YES
local_umask=022

dirmessage_enable=YES
use_localtime=YES
xferlog_enable=YES
connect_from_port_20=YES

secure_chroot_dir=/var/run/vsftpd/empty
pam_service_name=vsftpd

# --- CELAH: IZIN TULIS BUAT ANON ---
# anon_upload_enable=YES
# anon_mkdir_write_enable=YES